### ISSUE TITLE
diconnected event not firing

### ISSUE THREAD

**Issue by dkebler** [home-assistant/home-assistant-js-websocket#106]
Got a working custom socket client and the api is working fine via it.

Just wanting to confirm that the module will notice when it's disconnected and attempt reconnect 

When I add a listener

`hass.conn.addEventListener('disconnected', () => console.log('disconnected'))`

and then disable my Ethernet port this event never fires.  

wondering if my custom createSocket is the issue?

I looked a bit into the code and I see that although pong is parsed message receive from the ha websocket you don't have a interval set up to ping.   #7  

https://developers.home-assistant.io/docs/en/external_api_websocket.html#pings-and-pongs

Still, when I enable the Ethernet port the connection is still there and the createSocket was not called again so just wondering what (if anything) this module does to monitor the connection? 

Apparently it does per the readme 

but 
https://github.com/home-assistant/home-assistant-js-websocket/blob/master/lib/connection.ts#L298

only gets called here

https://github.com/home-assistant/home-assistant-js-websocket/blob/master/lib/connection.ts#L101

and that is only if the socket's close listener called  which maybe doesn't happen with my custom socket client?

`socket.addEventListener("close", ev => this._handleClose(ev));` 

My socket supports addEventListener so not sure why the Connection class is not firing the 'disconnected' event when network link is broken.

Is if up to me to ping server and take action when connection is lost?

**Comment by balloob** [comment]
We no longer send pings, assuming that websocket heartbeats take care of it . Does it not ? Otherwise 60 seconds would be a long time to realize something is off. 

`disconnected` works in the browser, as we show the "No connection available, reconnecting…" toast if we're disconnected.

**Comment by dkebler** [comment]
little more digging.  The faye socket uses the faye socket driver and has a built in ping from server event.   

If I do this I see the heartbeat from ha websocket server
```
    let last_ping = Date.now()
    this.conn.socket._driver.on('ping', () => {
      let now = Date.now()
      let diff = last_ping - now
      last_ping = now
      console.log(`ping received in ${diff} seconds`)
    })
```

```
ping received in 55 seconds
ping received in 55 seconds
ping received in 55 seconds
...
```

The ha websocket server must be an old dying man.  It's heartbeat is only every approx 55 seconds.   Really not often enough IMO.  So I guess I can still send pings more frequently.  

Bottom line is I have to set up my own disconnect monitor.
Looks like I want to call conn._handleClose whenever there is a connection issue (i.e. no ping from server or otherwise closed) right?

It's "private" but I can still call it.  Maybe it there should be a public method (part of api) on the class to access it.  The reconnect should work since it calls my passed createSocket.  Maybe it should be name `handleDisconnect` or just `reconnect`

```
  private _handleClose(ev: CloseEvent) {
    // Reject in-flight sendMessagePromise requests
    this.commands.forEach(info => {
      // We don't cancel subscribeEvents commands in flight
      // as we will be able to recover them.
      if (!("subscribe" in info)) {
        info.reject(messages.error(ERR_CONNECTION_LOST, "Connection lost"));
      }
    });

    if (this.closeRequested) {
      return;
    }

    this.fireEvent("disconnected");

    // Disable setupRetry, we control it here with auto-backoff
    const options = { ...this.options, setupRetry: 0 };

    const reconnect = (tries: number) => {
      setTimeout(async () => {
        if (DEBUG) {
          console.log("Trying to reconnect");
        }
        try {
          const socket = await options.createSocket(options);
          this.setSocket(socket);
        } catch (err) {
          if (err === ERR_INVALID_AUTH) {
            this.fireEvent("reconnect-error", err);
          } else {
            reconnect(tries + 1);
          }
        }
      }, Math.min(tries, 5) * 1000);
    };

    reconnect(0);
  }
```


Also .setSocket has some socket specific code, the two add Listeners.  I think it will work for my socket because they back supported addEventListener but that doesn't have to be the case.   I will see if I can call socket.close and make this work.  If so that's a way to hook in my alt socket health monitoring.  I only wonder why a timed out pong doesn't seem to emit a close.  You'd think so.   

```
  setSocket(socket: WebSocket) {
    const oldSocket = this.socket;
    this.socket = socket;
    socket.addEventListener("message", ev => this._handleMessage(ev));
    socket.addEventListener("close", ev => this._handleClose(ev));

    if (oldSocket) {
      const oldCommands = this.commands;

      // reset to original state
      this.commandId = 1;
      this.commands = new Map();

      oldCommands.forEach(info => {
        if ("subscribe" in info) {
          info.subscribe().then(unsub => {
            info.unsubscribe = unsub;
            // We need to resolve this in case it wasn't resolved yet.
            // This allows us to subscribe while we're disconnected
            // and recover properly.
            info.resolve();
          });
        }
      });

      this.fireEvent("ready");
    }
  }

**Comment by balloob** [comment]
Home Assistant JS Websocket works with the WebSocket class that is available in browsers. If you are using Node, you need to use a polyfill that provides the exact same API. Handle Close should not be public, as the disconnect event should fire properly.

**Comment by dkebler** [comment]
Well I have a working ping/pong monitor.  It's added as a method to the socket when it's created.  

I have a bit of a catch-22 though and it involves having to know the value off .commandId when sending the pings.  Can't do that without having a connection instance and ._handleClose only calls createSocket which doesn't know about commandId.   If I call the ping pong monitor after createSocket that's fine for the first time but won't work if createSocket is called again...arrh.

Do you know of a way in the HA settings to tell the web socket to sends pings more frequently?  If so I don't need to do any of this if not I just might spin my own HA connection class.  I'm half way there already :-).
