### ISSUE TITLE
JsFiddle example is wrong

### ISSUE THREAD

**Issue by JerryWorkman** [home-assistant/home-assistant-js-websocket#12]
Your JsFiddle example if for a different API.

**Comment by balloob** [comment]
Just verified. It works.

![image](https://user-images.githubusercontent.com/1444314/35198899-9ceca2e6-feaa-11e7-9b6e-dab150e969dd.png)

When including this package via the UMD bundle, you have to access the objects on `HAWS`.

**Comment by JerryWorkman** [comment]
Yes, The fiddle works but with different code than the Github source. Is there another example?

**Comment by JerryWorkman** [comment]
I want to do this using Polymer and Websocket:
https://gist.github.com/JerryWorkman/31987605cd4958864dd5f159e26c0408
