### ISSUE TITLE
Missing setState method?

### ISSUE THREAD

**Issue by danitetus** [home-assistant/home-assistant-js-websocket#14]
I know that it's better to use services to modify the components states, but for testing purposes sometimes we need to change the state directly without using the services. This is possible to do with the RESTFUL API, but I can't find the method in this library.

Am I missing something?

Thanks

PS: Sorry but english is not my native language.

**Comment by balloob** [comment]
That is not possible via the websocket API https://developers.home-assistant.io/docs/en/external_api_websocket.html

Neither should all commands be added to this lib. Commands can always be send via sendMessagePromise
