### ISSUE TITLE
Commit causes all kind of issues with frontend

### ISSUE THREAD

**Issue by quaqo** [home-assistant/home-assistant-js-websocket#229]
See here:

https://github.com/home-assistant/frontend/issues/11039#issuecomment-1002309735

**Comment by frenck** [comment]
There is no need to open issues in all places, the linked issue is fine for tracking this.

**Comment by quaqo** [comment]
> There is no need to open issues in all places, the linked issue is fine for tracking this.

Usually the issue is tracked in the repository where the component lies. I apologize.
