### ISSUE TITLE
Method to bypass authentication phase?

### ISSUE THREAD

**Issue by SuddenlyEngineer** [home-assistant/home-assistant-js-websocket#270]
I am developing an integration for a closed source piece of hardware I would like to use to control HA. I have created a long lived authentication token for the websocket connection, but I cannot get past the authentication flow. While I am trying to escalate to the OEM, I was wondering if there was a way to skip the authentication piece, perhaps by appending something like `?type=auth&access_token=` to the URL, and going straight to the command phase of the websocket connection.

**Comment by balloob** [comment]
We don't add authentication tokens to URLs with Home Assistant as they can get logged.
