### ISSUE TITLE
Way to limit entities?

### ISSUE THREAD

**Issue by mdewyer** [home-assistant/home-assistant-js-websocket#271]
I have a ~400 entities but only want to work with the data of less than 10. Is there a way I can limit / filter the entities subscribed to avoid all the unnecessary data for the other few hundred being transmitted and processed? Thanks!

**Comment by balloob** [comment]
Use `subscribe_entities`
https://github.com/home-assistant/core/blob/dev/homeassistant/components/websocket_api/commands.py#L269-L270

**Comment by Timmiej93** [comment]
Unfortunately, I'm now stuck with the same issue. I want to use just a few entities, but I can't figure out how to. The link no longer reflects anything useful (at least it doesn't seem to). The `subscribeEntities` function also seems to only offer a subscription to all available entities in HA. Am I misreading something, or is this no longer possible?

**Comment by jeffre** [comment]
@Timmiej93 I am in a similar place and used a very ugly hack to get it done (apologies to all js devs). Include an `entity_ids` list inside the `const subscribeUpdates` section within your file at `./dist/entities.js`. Mine looks like this:
```js
const subscribeUpdates = (conn, store, entity_ids) => conn.subscribeMessage((ev) => processEvent(store, ev), {
    type: "subscribe_entities",
    entity_ids: [
        "cover.garage",
    ],
});
```
