### ISSUE TITLE
Raw message possible to read media image?

### ISSUE THREAD

**Issue by RonnyWinkler** [home-assistant/home-assistant-js-websocket#323]
Hi,
I tried to use the raw message to retrieve the media thumbnail for a media player entity.

```
connection.sendMessagePromise(
  {
    "id": 19,
    "type": "media_player_thumbnail",
    "key": this.entityId
  }
)
```

I got only an error message "unknown command" as result.
Isn't it possible to use the messages from this documentation?
https://developers.home-assistant.io/docs/api/websocket#fetching-media-player-thumbnails
Or am I doing something wrong (parameters)?

A simple ping was also not working with this function. But there is a dedicated function for the connection to send a ping message.
Is a dedicated function also needed for media thumbnails?

Thanks for any hint.
Ronny

**Comment by balloob** [comment]
That method was removed as it was blocking the whole websocket, hurting performance. 

Your method of calling is correct, although you should drop the message ID, it's automatically handled for you.

**Comment by RonnyWinkler** [comment]
Thanks for your answer. I tried again with the sendMessagePromise function but got an error again.

Function call:
`let result = await this._connection.sendMessagePromise(message);`

Parameter:
```
        {
            "type": "media_player_thumbnail",
            "key": this.entityId
        }
```

Result:
![grafik](https://user-images.githubusercontent.com/49495550/201474661-5053cdd4-433a-4cec-a266-6a57c27502e5.png)

The entity itself has image references.
![grafik](https://user-images.githubusercontent.com/49495550/201474761-01f4776a-0e49-44d4-a2de-ffb63b744fbb.png)

Is the function dependent on the entity and the entity must support the image reading? Or is that a core functionality.

**Comment by RonnyWinkler** [comment]
> That method was removed as it was blocking the whole websocket, hurting performance.

Oh, did you mean the "type": "media_player_thumbnail" was removed completely from HA side? Or just the wrapper function in the npm module?

**Comment by RonnyWinkler** [comment]
I figured out that the media player has an attribute with local image URL, that can be used to read the image via http using the HA server IP:port. 
I'll go this way :)
