### ISSUE TITLE
pre-release tagged as latest in npm

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-js-websocket#33]
# Problem

It looks like the pre-release version of this package has been published to [npm](https://www.npmjs.com/package/home-assistant-js-websocket) as latest:

![screenshot](https://user-images.githubusercontent.com/28114703/43971542-60898108-9cc9-11e8-9d92-641aab974503.png)

Since this is a pre-release, I don't believe this should be published as latest in npm

*I discovered this from upgrading my packages, which I had to revert since the new oauth2 system is not in mass use as of yet*

**Comment by balloob** [comment]
I was assuming that npm would not tag a rc as latest. Weird

**Comment by timmo001** [comment]
I think you have to specifically tag the release with npm:

https://docs.npmjs.com/getting-started/using-tags

**Comment by balloob** [comment]
Finally managed. It won't prompt you but you need to add `--otp 123456` with your 2FA code if you have that enabled.

![image](https://user-images.githubusercontent.com/1444314/43989040-cd967e26-9d42-11e8-9a7e-cbc301f304d2.png)
