### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by apasellaits** [home-assistant/home-assistant-js-websocket#463]
<img width="754" alt="image" src="https://github.com/home-assistant/home-assistant-js-websocket/assets/100215798/207805d7-2c14-437d-9c5d-662494325507">

**Comment by balloob** [comment]
Works here. Maybe a glitch for Glitch

![CleanShot 2024-01-31 at 11 44 10](https://github.com/home-assistant/home-assistant-js-websocket/assets/1444314/d936b47a-0527-4199-b1cf-9cd11f889218)
