### ISSUE TITLE
Connection class doesn't resubscribe to events if event_type empty

### ISSUE THREAD

**Issue by zachowj** [home-assistant/home-assistant-js-websocket#57]
Not sure if this is intended but if you subscribe to subscribe_events with an empty event_type the connection class won't resubscribe to subscribe_events on a reconnect to the websocket.

https://github.com/home-assistant/home-assistant-js-websocket/blob/ff15397fa19f1945f292b6c482e7ba06fd0ba6dd/lib/connection.ts#L89-L110

**Comment by balloob** [comment]
Yeah that is weird 🤔

**Comment by balloob** [comment]
Could you share what you're building?

**Comment by zachowj** [comment]
I have forked [node-red-contrib-home-assistant](https://github.com/Spartan-II-117/node-red-contrib-home-assistant) and have converted it to start using websocket and the new auth system, well once you guys release the long-lived access token (https://github.com/home-assistant/home-assistant/pull/16453).

Hopefully plan on having something pushed to the public in short order. It's my first real big open source project and pretty sure that I am trying to make it to prefect before releasing it.

**Comment by balloob** [comment]
That's awesome!
