### ISSUE TITLE
Unexpected token N in JSON

### ISSUE THREAD

**Issue by timmo001** [home-assistant/home-assistant-js-websocket#80]
## Problem

I keep getting these errors and am unable to resolve the issue. I'm not sure if there is an issue in `home-assistant` itself, sending bad JSON or bad config, but it is causing issues with HASS and my webapp. I end up getting a ton of logs in HASS and console errors in my app. Occasionally I have to reload the page as the error is very inconsistent.

`Unexpected token N in JSON at position SOME_POSTION`

## Screenshots

![image](https://user-images.githubusercontent.com/28114703/48979321-32fb2e80-f0b1-11e8-9b03-49a34fa24eab.png)

![image](https://user-images.githubusercontent.com/28114703/48979337-53c38400-f0b1-11e8-80ce-7886e1134322.png)

![image](https://user-images.githubusercontent.com/28114703/48979325-3e4e5a00-f0b1-11e8-971a-9b3d017a1b5b.png)

![image](https://user-images.githubusercontent.com/28114703/48979329-460dfe80-f0b1-11e8-9a13-ad817b22d3ab.png)

**Comment by balloob** [comment]
In Chrome, on the network tab, select the websocket connection and see what data is being send and if that's valid JSON

![image](https://user-images.githubusercontent.com/1444314/48980158-af980800-f0c5-11e8-8dd9-0e24cafdd6c1.png)

**Comment by timmo001** [comment]
Ah. Looks like this data occasionally gets sent:

```json
{
   "id":20,
   "type":"result",
   "success":true,
   "result":null
}
```

Perhaps we need a check to see if there is the `data` object before calling update?

**Comment by timmo001** [comment]
Oh! Looks like my climate component is sending `NaN` for the `current_temperature`:

```json
{
   "id":2,
   "type":"event",
   "event":{
      "event_type":"state_changed",
      "data":{
         "entity_id":"climate.central_heating",
         "old_state":{
            "entity_id":"climate.central_heating",
            "state":"off",
            "attributes":{
               "current_temperature":21.9,
               "min_temp":10.0,
               "max_temp":30.0,
               "temperature":22.0,
               "operation_mode":"off",
               "operation_list":[
                  "heat",
                  "off"
               ],
               "away_mode":"off",
               "friendly_name":"Central Heating",
               "supported_features":1153
            },
            "last_changed":"2018-11-25T14:14:16.009505+00:00",
            "last_updated":"2018-11-25T15:07:46.923499+00:00",
            "context":{
               "id":"13f5cc7225794966a98f352c458cf6e8",
               "user_id":null
            }
         },
         "new_state":{
            "entity_id":"climate.central_heating",
            "state":"off",
            "attributes":{
               "current_temperature":NaN,
               "min_temp":10.0,
               "max_temp":30.0,
               "temperature":22.0,
               "operation_mode":"off",
               "operation_list":[
                  "heat",
                  "off"
               ],
               "away_mode":"off",
               "friendly_name":"Central Heating",
               "supported_features":1153
            },
            "last_changed":"2018-11-25T14:14:16.009505+00:00",
            "last_updated":"2018-11-25T15:07:57.207862+00:00",
            "context":{
               "id":"d2e1be20ebbd47289de299865253f333",
               "user_id":null
            }
         }
      },
      "origin":"LOCAL",
      "time_fired":"2018-11-25T15:07:57.207894+00:00",
      "context":{
         "id":"d2e1be20ebbd47289de299865253f333",
         "user_id":null
      }
   }
}
```

Going to look into this and open up a PR over at the main repo if there is a bug in the `generic_thermostat` component or not. I guess the above gets caused by this line:

```json
               "current_temperature":NaN,
```

**Comment by timmo001** [comment]
Looks like it might be more the fault of my MQTT sensor sending null data every now and then. Not exactly sure why, It might be down to the actual component updating the data as NaN which might need handling.

Thanks for the pointer! I'll close this since it's not related to the websocket :+1:

**Comment by balloob** [comment]
@timmo001 you want to open a PR to prevent the MQTT integration from even publishing a `NaN` number ?
