### ISSUE TITLE
UnhandledRejection in subscribeEvents when connection is closed before receiving response

### ISSUE THREAD

**Issue by zachowj** [home-assistant/home-assistant-js-websocket#98]
Issue #65 has reappeared or something very similar to it.

https://gist.github.com/zachowj/3bad002cd0ba3b5cd61dbfd47aecb3b5 is a demo of error in action.

Last working with v3.1.6
Tested and fails with v3.2.0 and v4.2.0

**Comment by balloob** [comment]
Without testing it, I suspect it was introduced in #74 when fixing #71.

**Comment by balloob** [comment]
Confirmed it's introduced in #74.
